### ISSUE TITLE
Add "Expertise" to header nav

### ISSUE THREAD

**Issue by melanierichards** [FlintMade/mediaplus#112]

**Comment by melanierichards** [comment]
Done! But when it launches make sure that the URL updates with the database URL switcheroo. If not, might need to fix.

**Comment by flintdesign** [comment]
Hi @melanierichards ... on the call today we convinced them to kill "expertise" in the navigation. Sorry for the flip-flop but could we remove it from the hamburger nav?

**Comment by melanierichards** [comment]
Done!
