### ISSUE TITLE
Channels and services on team page

### ISSUE THREAD

**Issue by flintdesign** [FlintMade/mediaplus#116]
Since we moved this to the Expertise section on homepage, they would like to remove Channels and Services from the "team" page. Can we move text section under "our team"?

![image](https://user-images.githubusercontent.com/12940384/28439280-14dbc890-6d56-11e7-9374-d2232fe6e0d7.png)

**Comment by flintdesign** [comment]
Scrap moving "X chromosomes section" over... @wes-anderson advised leaving it but aligning it with our team hang-line.

**Comment by melanierichards** [comment]
@flintdesign as a heads up, the text off to the right was unaligned with the title because someone had typed some extra spaces into the content box in Wordpress. Just in case that happens again elsewhere!
