### ISSUE TITLE
Contact Page hover states

### ISSUE THREAD

**Issue by wes-anderson** [FlintMade/mediaplus#53]
- hover states should be #f35a00 (remove the current underline hover state)

**Comment by melanierichards** [comment]
@wes-anderson we should consider keeping the hover states for accessibility reasons. If a person can't see color, it might not look like anything changed.

**Comment by wes-anderson** [comment]
Okay. lets do the combo. and thicken up the line to 2-3px

**Comment by melanierichards** [comment]
Word! Thanks
