### ISSUE TITLE
Mobile Menu

### ISSUE THREAD

**Issue by wes-anderson** [FlintMade/mediaplus#55]
-loading super slow
-decrease the space between menu items
-when menu is open please lock background content in space. I should not be able to scroll

**Comment by melanierichards** [comment]
Oops, changed the load times to debug something and forgot to change them back. Sorry about that!

I've actually already reduced the space between since last time you mentioned it. I'll reduce it more but we should probably go over it in person too! :)

**Comment by melanierichards** [comment]
Changes:

* Make tray 60% width
* Make nav font size 2rem
* Make top margin on li .75rem
