### ISSUE TITLE
Client Page - mobile

### ISSUE THREAD

**Issue by wes-anderson** [FlintMade/mediaplus#58]
-Does not seam to be working.
-I cannot filter
-i am unable to click the client rows

**Comment by melanierichards** [comment]
@wes-anderson what phone and OS are you on? This is working fine for me on iPhone w/ iOS 10. I'm wondering if there's a script that's not loading or cached or something...

**Comment by wes-anderson** [comment]
I was on chrome. i'll do a hard restart to double check

**Comment by melanierichards** [comment]
You can also try using Chrome in a "Guest" tab, I think that clears your cache.
