### ISSUE TITLE
M+ Notes - 3 July, 2017

### ISSUE THREAD

**Issue by wes-anderson** [FlintMade/mediaplus#7]
# DESKTOP

**General Animation Notes**
-would really love to add in some nice slow load stuff - www.eastdining.com.au/ OR www.danielhopwood.com OR http://www.coyyiontis.com.au

**IMG Gallery**
- Click anywhere on the img area 50% left / right advance img in that direction.

**Home Page**
-N/A

**Expertise**
-N/A
- www.olsonkundig.com/projects/pavilion-house/ - Example for expertise page transition. (scroll to bottom of page and you will see.)
- _click the side bar sub nav it should just load the expertise i click. No need to scroll past other sections. BUT if I am just scrolling I should be able to scroll from the first expertise all the way down to the last one and have eact next section do the slow load (www.olsonkundig.com/projects/pavilion-house/)._

**About Page**
-Missing Headline

Photo / bio area
-spacing between job title & “More info+” is to much
- remove full image fade on hover
- “More info+” Hover should be #f45a00
	-On click 
		01) Grey full color fade in from Bottom to top (www.danielhopwood.com - see page transitions for example)
		02) Text Fade in Top to Bottom 
- “-Close info” hover should be #f45a00
	-On click 
		01) Text Fade out
		02) Grey fade out top to bottom (www.danielhopwood.com - see page transitions for example)
- I believe the personal email will need to be a clickable mailto link

_Approach page
- hold on this we may ad it as a subpage under about._

**Clientele Page**
- We May need to add in a description area under each client. This would be a max character limit.
- Can we make each row hoverable 
- If multiple processes for a client can we show the number - if 5 “(05)” see comps for example.
- no need to filter by multiple processes

**Contact Page**
Bump headline & subtext up to 16px

** @Journal Page**
- Totally cool with the date in placement of the gallery! looks good.
-  love your idea for image pacing lets go with that.

**Journal Post**
_- Page format should basically be the same as the about page._
**Menu**
On Hover #f45a00 (remove grow on hover) 
“about clients contact journal” could this please slow fade in animate from top to bottom.
- Menu pages should stay open on all pages except the  intro / Expertise / offerings 
	- moment someone click the “X” site would take you back to the expertise section you were last on. (I can talk more to this in person)

**Footer** 
-Hover states- #f45a00
- (remove underline hover state)

# MOBILE

**General Notes**
-Hard to give feedback on typography at this time. Site won’t load the font for me even though i have it installed.
	- increase body type size to 15px (may change once actual type is installed)

**Menu**
- Tight up the leading space between “about clients contact journal”

**About Page**
-Missing Headline
- Offerings / services goes below the intro paragraph.
- Employee photos are all different heights.
-For mobile if the full photo tile is clickable that is fine.

**Contact Page**
- The Type in the Inquiries section seems super small ( i think this i a mistake in the comps AKA my fault)
	- Bump headlines up to 16px 

**Journal Page**
- looks good

**Journal Post**
- bullet points break free from the grid / go beyond the gutter

**Comment by melanierichards** [comment]
Going to close this because I think everything's captured in individual issues now
