### ISSUE TITLE
Change case study load animation to slow fade

### ISSUE THREAD

**Issue by wes-anderson** [FlintMade/mediaplus#82]
Lets remove the swipe fade animation on the case study section

**Comment by melanierichards** [comment]
@wes-anderson just want to make sure you mean for everything, including the transition from the home intro

**Comment by wes-anderson** [comment]
I just mean the actually case study content. SO any time case study content (excluding the side bar nav / page transition swipe) comes in if that can just slow fade without the swipe up that would be great. @melanierichards

**Comment by melanierichards** [comment]
Cool, thanks!
