### ISSUE TITLE
Scrolling once a vertical is clicked

### ISSUE THREAD

**Issue by flintdesign** [FlintMade/mediaplus#88]
On homepage, once you click a vertical on left-hand sidebar (orange) it locks you into that vertical and you can't scroll to next one, or the prompt to go to the next one doesn't pop up. This is in chrome.

**Comment by melanierichards** [comment]
@flintdesign hrm, I had pushed a fix for this earlier today. Just put a cache bust string on the JS file...would you mind trying the following:

1. Hard refresh and see if it works
2. If still broken, open the site in a Chrome "Guest" window and see if it works

If it's still not working for you, we can go over it in person.

**Comment by melanierichards** [comment]
I ended up hitting this too and figured out that it was happening under very specific conditions. Pushed up a fix!
