### ISSUE TITLE
Menu Hover color Bug

### ISSUE THREAD

**Issue by wes-anderson** [FlintMade/mediaplus#89]
when i am on the expertise section and click the menu and then close it. the menu is currently keeping the yellow hover state color. when i click somewhere else on the page the color reverts back to the grey.

The menu should only be the yellow on open or hover...

**Comment by melanierichards** [comment]
I have the focus state set to current section color. We have a few open tasks about managing focus state so let's talk through that again (`:focus` state is activated on a link, button, etc via a click or a tab)
